# Generated by Django 5.2.3 on 2025-06-12 23:38

import st.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_alter_user_options_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instruction_manual',
            field=models.FileField(blank=True, null=True, upload_to=st.models.product_instruction_path, verbose_name='Инструкция (PDF/DOC)'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_url',
            field=models.URLField(blank=True, help_text='Например, https://www.apple.com', null=True, verbose_name='Сайт производителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_online', 'Картой онлайн'), ('cash_pickup', 'Наличными при самовывозе'), ('courier_cash', 'Курьеру наличными'), ('courier_card', 'Курьеру картой')], default='card_online', max_length=50, verbose_name='Метод оплаты'),
        ),
    ]
